export interface Project {
  id: number
  title: string
  description: string
  category: string
  status: "Completed" | "In Progress" | "Planning"
  image: string
  technologies: string[]
  team: string[]
  timeline: string
  githubUrl?: string
  demoUrl?: string
  paperUrl?: string
  achievements?: string
  technicalDetails: string[]
}

export const projects: Project[] = [
  {
    id: 1,
    title: "Smart Campus Navigation System",
    description:
      "An AI-powered mobile app that helps students navigate Pasadena City College campus using computer vision and natural language processing. The system provides real-time directions, identifies buildings and landmarks, and answers questions about campus facilities.",
    category: "Computer Vision",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=Campus+Navigation+AI",
    technologies: ["Python", "TensorFlow", "OpenCV", "React Native", "Firebase", "Google Maps API"],
    team: ["Sarah Chen", "Marcus Rodriguez", "Alex Thompson", "Jennifer Liu"],
    timeline: "Sep 2023 - Feb 2024",
    githubUrl: "https://github.com/pcc-ai-club/campus-navigation",
    demoUrl: "https://campus-nav-demo.vercel.app",
    achievements: "Winner of PCC Innovation Challenge 2024, 500+ active users",
    technicalDetails: [
      "Implemented YOLO v8 for real-time object detection of campus landmarks and signage",
      "Developed custom dataset with 10,000+ labeled images of PCC campus locations",
      "Integrated Google Maps API with custom pathfinding algorithms for indoor navigation",
      "Built natural language interface using BERT for processing user queries about campus facilities",
      "Deployed mobile app using React Native with offline capability for map data",
      "Achieved 94% accuracy in landmark recognition and 98% user satisfaction rating",
    ],
  },
  {
    id: 2,
    title: "AI-Powered Study Buddy Chatbot",
    description:
      "A conversational AI assistant designed to help students with their coursework. The chatbot can answer questions about various subjects, provide study tips, create practice quizzes, and offer personalized learning recommendations based on individual progress.",
    category: "NLP",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=Study+Buddy+Chatbot",
    technologies: ["Python", "Transformers", "Hugging Face", "FastAPI", "React", "PostgreSQL", "Docker"],
    team: ["Aisha Patel", "David Kim", "Emily Johnson", "Robert Garcia"],
    timeline: "Jan 2024 - May 2024",
    githubUrl: "https://github.com/pcc-ai-club/study-buddy",
    demoUrl: "https://study-buddy.pcc-ai.org",
    achievements: "Deployed across 5 community colleges, 2,000+ student users",
    technicalDetails: [
      "Fine-tuned GPT-3.5 on educational content from multiple academic disciplines",
      "Implemented retrieval-augmented generation (RAG) for accessing course-specific materials",
      "Built adaptive learning system that personalizes content based on student performance",
      "Created automated quiz generation using natural language processing techniques",
      "Developed conversation memory system to maintain context across study sessions",
      "Integrated with Canvas LMS for seamless access to course materials and assignments",
    ],
  },
  {
    id: 3,
    title: "Predictive Maintenance for Lab Equipment",
    description:
      "A machine learning system that predicts when laboratory equipment needs maintenance by analyzing sensor data, usage patterns, and historical maintenance records. This helps reduce downtime and prevents costly equipment failures.",
    category: "Machine Learning",
    status: "In Progress",
    image: "/placeholder.svg?height=400&width=600&text=Predictive+Maintenance+ML",
    technologies: ["Python", "Scikit-learn", "Pandas", "InfluxDB", "Grafana", "IoT Sensors", "MQTT"],
    team: ["Alex Thompson", "Michael Chang", "Lisa Wang", "Priya Sharma"],
    timeline: "Mar 2024 - Aug 2024",
    githubUrl: "https://github.com/pcc-ai-club/predictive-maintenance",
    achievements: "Reduced equipment downtime by 35% in pilot program",
    technicalDetails: [
      "Deployed IoT sensors on 50+ pieces of lab equipment to collect real-time operational data",
      "Implemented time series analysis using LSTM networks for failure prediction",
      "Built ensemble models combining Random Forest and XGBoost for maintenance scheduling",
      "Created real-time dashboard using Grafana for monitoring equipment health status",
      "Developed automated alert system that notifies maintenance staff of potential issues",
      "Achieved 87% accuracy in predicting equipment failures 2-4 weeks in advance",
    ],
  },
  {
    id: 4,
    title: "Automated Essay Grading System",
    description:
      "An NLP-based system that assists instructors in grading student essays by analyzing writing quality, grammar, coherence, and content relevance. The system provides detailed feedback and suggestions for improvement while maintaining consistency in grading standards.",
    category: "NLP",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=Essay+Grading+AI",
    technologies: ["Python", "spaCy", "NLTK", "Transformers", "Flask", "SQLite", "Bootstrap"],
    team: ["Aisha Patel", "Jennifer Liu", "Marcus Rodriguez"],
    timeline: "Aug 2023 - Dec 2023",
    githubUrl: "https://github.com/pcc-ai-club/essay-grader",
    demoUrl: "https://essay-grader-demo.herokuapp.com",
    paperUrl: "https://arxiv.org/abs/2024.essay.grading",
    achievements: "Published research paper, adopted by 3 PCC English departments",
    technicalDetails: [
      "Trained custom BERT model on dataset of 15,000+ graded essays from multiple disciplines",
      "Implemented multi-criteria evaluation system covering grammar, coherence, and content quality",
      "Built automated feedback generation system providing specific suggestions for improvement",
      "Created calibration system allowing instructors to adjust grading standards and rubrics",
      "Developed plagiarism detection component using semantic similarity analysis",
      "Achieved 0.85 correlation with human graders across different essay types and subjects",
    ],
  },
  {
    id: 5,
    title: "Real-time Emotion Recognition System",
    description:
      "A computer vision application that detects and analyzes human emotions in real-time using facial expression recognition. The system can be used for accessibility applications, user experience research, and educational tools.",
    category: "Computer Vision",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=Emotion+Recognition+CV",
    technologies: ["Python", "OpenCV", "TensorFlow", "Keras", "MediaPipe", "Streamlit"],
    team: ["Marcus Rodriguez", "Sarah Chen", "David Kim"],
    timeline: "Oct 2023 - Jan 2024",
    githubUrl: "https://github.com/pcc-ai-club/emotion-recognition",
    demoUrl: "https://emotion-recognition.streamlit.app",
    achievements: "Presented at California AI Symposium 2024",
    technicalDetails: [
      "Implemented convolutional neural network architecture optimized for facial emotion detection",
      "Trained on FER-2013 dataset with data augmentation techniques for improved generalization",
      "Integrated MediaPipe for robust facial landmark detection and face alignment",
      "Built real-time processing pipeline capable of analyzing 30+ FPS video streams",
      "Developed privacy-preserving mode that processes emotions without storing facial data",
      "Achieved 89% accuracy across 7 emotion categories (happy, sad, angry, fear, surprise, disgust, neutral)",
    ],
  },
  {
    id: 6,
    title: "Smart Parking Management System",
    description:
      "An IoT and AI-powered solution for optimizing parking space utilization on campus. The system uses computer vision to detect available parking spots, predicts parking demand, and provides real-time information to drivers through a mobile app.",
    category: "Computer Vision",
    status: "In Progress",
    image: "/placeholder.svg?height=400&width=600&text=Smart+Parking+System",
    technologies: ["Python", "YOLOv8", "Raspberry Pi", "React Native", "Node.js", "MongoDB", "AWS IoT"],
    team: ["Alex Thompson", "Emily Johnson", "Michael Chang", "Lisa Wang"],
    timeline: "Feb 2024 - Sep 2024",
    githubUrl: "https://github.com/pcc-ai-club/smart-parking",
    achievements: "Pilot deployment in PCC main parking lot, 40% reduction in parking search time",
    technicalDetails: [
      "Deployed network of Raspberry Pi cameras with YOLOv8 models for parking space detection",
      "Implemented time series forecasting to predict parking demand patterns throughout the day",
      "Built mobile app with real-time parking availability and reservation system",
      "Created edge computing solution for local processing to reduce bandwidth and latency",
      "Developed machine learning model to optimize parking space allocation based on user patterns",
      "Integrated with campus security system for automated violation detection and reporting",
    ],
  },
  {
    id: 7,
    title: "Medical Image Analysis for Skin Cancer Detection",
    description:
      "A deep learning application that assists dermatologists in early detection of skin cancer by analyzing dermoscopic images. The system provides risk assessment and highlights suspicious areas for further examination.",
    category: "Machine Learning",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=Skin+Cancer+Detection",
    technologies: ["Python", "PyTorch", "Torchvision", "Gradio", "MONAI", "Docker", "AWS"],
    team: ["Sarah Chen", "Aisha Patel", "Jennifer Liu"],
    timeline: "Nov 2023 - Apr 2024",
    githubUrl: "https://github.com/pcc-ai-club/skin-cancer-detection",
    demoUrl: "https://skin-cancer-detector.gradio.app",
    paperUrl: "https://arxiv.org/abs/2024.skin.cancer.detection",
    achievements: "Collaboration with PCC Health Center, 92% sensitivity in melanoma detection",
    technicalDetails: [
      "Trained EfficientNet-B7 model on HAM10000 dataset with 10,015 dermatoscopic images",
      "Implemented advanced data augmentation including color jittering and geometric transformations",
      "Built ensemble model combining multiple architectures for improved diagnostic accuracy",
      "Created attention visualization system to highlight suspicious regions in skin lesions",
      "Developed DICOM integration for seamless workflow with medical imaging systems",
      "Achieved 94% accuracy in distinguishing benign from malignant skin lesions",
    ],
  },
  {
    id: 8,
    title: "Autonomous Drone Navigation System",
    description:
      "A computer vision and reinforcement learning system that enables drones to navigate autonomously through complex environments. The project focuses on obstacle avoidance, path planning, and real-time decision making.",
    category: "Hardware",
    status: "In Progress",
    image: "/placeholder.svg?height=400&width=600&text=Autonomous+Drone+System",
    technologies: ["Python", "ROS", "OpenCV", "PyTorch", "Gazebo", "PX4", "Raspberry Pi"],
    team: ["Alex Thompson", "Marcus Rodriguez", "David Kim", "Robert Garcia"],
    timeline: "Jan 2024 - Dec 2024",
    githubUrl: "https://github.com/pcc-ai-club/autonomous-drone",
    achievements: "Successful autonomous flight demonstrations, featured in local tech news",
    technicalDetails: [
      "Implemented SLAM (Simultaneous Localization and Mapping) for real-time environment mapping",
      "Developed reinforcement learning agent using PPO algorithm for navigation policy",
      "Built computer vision pipeline for obstacle detection and depth estimation using stereo cameras",
      "Created simulation environment in Gazebo for safe testing of navigation algorithms",
      "Integrated GPS-denied navigation using visual-inertial odometry techniques",
      "Achieved autonomous navigation in complex indoor environments with 95% success rate",
    ],
  },
  {
    id: 9,
    title: "AI-Powered Course Recommendation Engine",
    description:
      "A recommendation system that helps students choose courses based on their academic history, career goals, and learning preferences. The system uses collaborative filtering and content-based approaches to provide personalized suggestions.",
    category: "Machine Learning",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=Course+Recommendation+AI",
    technologies: ["Python", "Scikit-learn", "Pandas", "Flask", "React", "PostgreSQL", "Redis"],
    team: ["David Kim", "Emily Johnson", "Priya Sharma", "Michael Chang"],
    timeline: "Sep 2023 - Feb 2024",
    githubUrl: "https://github.com/pcc-ai-club/course-recommender",
    demoUrl: "https://course-recommender.pcc-ai.org",
    achievements: "Integrated with PCC student portal, 85% student satisfaction rate",
    technicalDetails: [
      "Implemented hybrid recommendation system combining collaborative and content-based filtering",
      "Built matrix factorization model using SVD for handling sparse student-course interaction data",
      "Created feature engineering pipeline incorporating GPA, major, and prerequisite information",
      "Developed cold start solution for new students using demographic and interest-based features",
      "Built A/B testing framework to continuously improve recommendation quality",
      "Achieved 78% accuracy in predicting courses students will successfully complete",
    ],
  },
  {
    id: 10,
    title: "Natural Language Query Interface for Databases",
    description:
      "A system that allows users to query databases using natural language instead of SQL. The application translates English questions into SQL queries and presents results in an intuitive format, making data analysis accessible to non-technical users.",
    category: "NLP",
    status: "Planning",
    image: "/placeholder.svg?height=400&width=600&text=NL+Database+Query",
    technologies: ["Python", "Transformers", "SQLAlchemy", "FastAPI", "Vue.js", "PostgreSQL"],
    team: ["Aisha Patel", "Alex Thompson", "Lisa Wang"],
    timeline: "Jun 2024 - Nov 2024",
    githubUrl: "https://github.com/pcc-ai-club/nl-database-query",
    achievements: "Secured funding from PCC Innovation Grant Program",
    technicalDetails: [
      "Planning to fine-tune T5 model for natural language to SQL translation tasks",
      "Designing schema-aware query generation system that understands database structure",
      "Building query validation and safety mechanisms to prevent harmful database operations",
      "Creating interactive interface for query refinement and result visualization",
      "Implementing support for complex queries including joins, aggregations, and subqueries",
      "Planning integration with multiple database systems including MySQL, PostgreSQL, and SQLite",
    ],
  },
  {
    id: 11,
    title: "Automated Plant Health Monitoring System",
    description:
      "An IoT and computer vision solution for monitoring plant health in the campus greenhouse. The system uses sensors and image analysis to detect diseases, monitor growth, and optimize growing conditions automatically.",
    category: "Computer Vision",
    status: "In Progress",
    image: "/placeholder.svg?height=400&width=600&text=Plant+Health+Monitoring",
    technologies: ["Python", "TensorFlow", "Arduino", "Raspberry Pi", "OpenCV", "InfluxDB", "Grafana"],
    team: ["Emily Johnson", "Sarah Chen", "Michael Chang"],
    timeline: "Apr 2024 - Oct 2024",
    githubUrl: "https://github.com/pcc-ai-club/plant-health-monitor",
    achievements: "Partnership with PCC Horticulture Department, 25% improvement in plant survival rate",
    technicalDetails: [
      "Developing convolutional neural network for plant disease classification using PlantVillage dataset",
      "Implementing multi-sensor data fusion combining visual, temperature, humidity, and soil sensors",
      "Building automated irrigation system controlled by machine learning predictions",
      "Creating time-lapse photography system for monitoring plant growth patterns",
      "Developing mobile app for greenhouse staff to receive alerts and view plant status",
      "Implementing edge computing solution for real-time processing of sensor and image data",
    ],
  },
  {
    id: 12,
    title: "AI Ethics and Bias Detection Tool",
    description:
      "A comprehensive toolkit for detecting and mitigating bias in machine learning models. The tool provides automated testing, visualization of bias patterns, and recommendations for improving model fairness across different demographic groups.",
    category: "Research",
    status: "Completed",
    image: "/placeholder.svg?height=400&width=600&text=AI+Ethics+Bias+Tool",
    technologies: ["Python", "Scikit-learn", "Fairlearn", "Streamlit", "Plotly", "Jupyter"],
    team: ["Marcus Rodriguez", "Aisha Patel", "Jennifer Liu", "Robert Garcia"],
    timeline: "May 2023 - Oct 2023",
    githubUrl: "https://github.com/pcc-ai-club/ai-ethics-toolkit",
    demoUrl: "https://ai-ethics-toolkit.streamlit.app",
    paperUrl: "https://arxiv.org/abs/2023.ai.ethics.toolkit",
    achievements: "Open-sourced toolkit with 500+ GitHub stars, presented at AI Ethics Conference 2024",
    technicalDetails: [
      "Implemented comprehensive bias detection algorithms for classification and regression models",
      "Built interactive dashboard for visualizing fairness metrics across different demographic groups",
      "Created automated report generation system highlighting potential bias issues and mitigation strategies",
      "Developed integration with popular ML frameworks including scikit-learn, TensorFlow, and PyTorch",
      "Implemented multiple fairness definitions including demographic parity and equalized opportunity",
      "Built educational component with tutorials and case studies on responsible AI development",
    ],
  },
]
